# configs/train/model_25m.yaml
hyperparameters:
  block_size: 64
  batch_size: 64

  # ~25M-ish model preset
  n_layer: 8
  n_head: 8
  d_model: 512

  d_compression: 128
  dropout: 0.1
  nb_features: 256

  lr: 0.0003
  weight_decay: 0.05
  evals_per_epoch: 3
  attn_type: "standard"
  epochs: 7
  seed: 1337

  log_file: "./logs/model_25m.log"
  data_dir: "./artifacts/datasets/hn_1m"
  output_dir: "./artifacts/runs/train/model_25m"

  accumulation_steps: 4

checkpointing:
  save_latest: true
  save_best: true
  save_step_checkpoints: true
  step_checkpoint_interval: 100