program: main/train.py
method: grid
metric:
  name: val_loss
  goal: minimize

command:
  - ${env}
  - python
  - ${program}
  - --sweep

parameters:
  config_path:
    values:
      - configs/sweep/train/scaling2/model5M.yaml
      - configs/sweep/train/scaling2/model7M.yaml
      - configs/sweep/train/scaling2/model9M.yaml
      - configs/sweep/train/scaling2/model15M.yaml
      - configs/sweep/train/scaling2/model22M.yaml
