# config.yaml
hyperparameters:
  block_size: 256
  batch_size: 256
  n_layer: 6
  n_head: 8
  d_model: 256
  d_compression: 128
  dropout: 0.4
  nb_features: 256
  lr: 0.01         # Scientific notation (6e-3) is also supported
  weight_decay: 0.07
  evals_per_epoch: 3
  attn_type: "sliding"
  epochs: 7
  seed: 1337
  log_file: "./logs/mainrun.log"
  data_dir: "./artifacts/datasets/hn_v1"
  output_dir: "./artifacts/runs/train"
  accumulation_steps: 2

checkpointing:
  save_latest: true
  save_best: true
  save_step_checkpoints: true
  step_checkpoint_interval: 100