# config.yaml
hyperparameters:
  block_size: 64
  batch_size: 64
  n_layer: 6
  n_head: 6
  d_model: 384
  d_compression: 128
  dropout: 0.1
  nb_features: 256
  lr: 0.003         # Scientific notation (6e-3) is also supported
  weight_decay: 0.05
  evals_per_epoch: 3
  attn_type: "standard"
  epochs: 7
  seed: 1337
  log_file: "./logs/mainrun.log"
  data_dir: "./artifacts/datasets/hn_1M"
  output_dir: "./artifacts/runs/train"
  accumulation_steps: 4

checkpointing:
  save_latest: true
  save_best: true
  save_step_checkpoints: true
  step_checkpoint_interval: 100

# eval:
#   eval_path: